import { Request, Response } from 'express';
import { prisma } from '../../index';
import { broadcastReferralOperational, broadcastUrgentEscalation } from '../../events/socket';
import { createNotification } from '../notifications/notification.service';

const VALID_TRANSITIONS: Record<string, string[]> = {
  'CREATED': ['SUBMITTED', 'CANCELLED'],
  'SUBMITTED': ['ACCEPTED', 'REJECTED'],
  'ACCEPTED': ['SCHEDULED'],
  'SCHEDULED': ['PATIENT_ARRIVED', 'CANCELLED'],
  'PATIENT_ARRIVED': ['IN_CONSULTATION'],
  'IN_CONSULTATION': ['DIAGNOSTICS_PENDING', 'TREATMENT', 'COUNTER_REFERRED'],
  'DIAGNOSTICS_PENDING': ['TREATMENT', 'COUNTER_REFERRED'],
  'TREATMENT': ['COUNTER_REFERRED'],
  'COUNTER_REFERRED': ['FOLLOW_UP_REQUIRED', 'COMPLETED'],
  'FOLLOW_UP_REQUIRED': ['COMPLETED']
};

export const createReferral = async (req: Request, res: Response) => {
  try {
    const { patientId, originId, destinationId, urgency, reason } = req.body;

    if (!patientId || !destinationId) {
      return res.status(400).json({ error: 'Bad Request', message: 'patientId and destinationId are required' });
    }

    const patient = await prisma.patient.findUnique({ where: { id: patientId } });
    if (!patient) {
      return res.status(404).json({ error: 'Not Found', message: 'Patient not found' });
    }

    const destFacility = await prisma.facility.findUnique({ where: { id: destinationId } });
    if (!destFacility) {
      return res.status(404).json({ error: 'Not Found', message: 'Destination facility not found' });
    }

    // Default origin to first facility if originId is missing or invalid
    let finalOriginId = originId;
    if (!finalOriginId) {
      const defaultFac = await prisma.facility.findFirst();
      finalOriginId = defaultFac?.id || destinationId;
    }

    const rawUrgency = String(urgency || 'ROUTINE').toUpperCase().trim();
    const validUrgencies = ['ROUTINE', 'PRIORITY', 'URGENT', 'EMERGENCY'];
    const finalUrgency = validUrgencies.includes(rawUrgency) ? rawUrgency : 'ROUTINE';
    const cleanReason = String(reason || 'Clinical referral').trim().slice(0, 500);

    const referral = await prisma.$transaction(async (tx) => {
      const ref = await tx.referral.create({
        data: {
          patientId,
          originId: finalOriginId,
          destinationId,
          urgency: finalUrgency,
          reason: cleanReason,
          status: 'SUBMITTED'
        }
      });

      await tx.referralEvent.create({
        data: {
          referralId: ref.id,
          statusFrom: 'CREATED',
          statusTo: 'SUBMITTED',
          notes: 'Referral generated by frontline health worker'
        }
      });

      return ref;
    });

    // Part B & H: Emit REFERRAL_OPERATIONAL_UPDATE
    broadcastReferralOperational(referral.originId, referral.destinationId, {
      referralId: referral.id,
      status: referral.status,
      urgency: referral.urgency,
      reason: referral.reason
    });

    // Part H & L: If urgent or emergency, emit URGENT_ESCALATION and notify assigned facility doctors
    if (referral.urgency === 'URGENT' || referral.urgency === 'EMERGENCY') {
      broadcastUrgentEscalation(referral.destinationId, {
        escalationType: 'REFERRAL_URGENT',
        entityId: referral.id,
        urgency: referral.urgency,
        reason: referral.reason
      });

      try {
        const assignedDocs = await prisma.facilityDoctor.findMany({
          where: { facilityId: referral.destinationId },
          include: { doctor: { select: { userId: true } } }
        });
        for (const fd of assignedDocs) {
          if (fd.doctor?.userId) {
            await createNotification(
              fd.doctor.userId,
              'URGENT_ESCALATION',
              `Urgent referral received: ${referral.urgency} priority for ${referral.reason}`
            );
          }
        }
      } catch {}
    }

    res.status(201).json(referral);
  } catch (error) {
    console.error('Error creating referral:', error);
    res.status(500).json({ error: 'Internal Server Error' });
  }
};

export const updateReferralStatus = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { newStatus, notes } = req.body;

    if (!id || typeof id !== 'string') {
      return res.status(400).json({ error: 'Bad Request', message: 'Referral ID is required' });
    }

    if (!newStatus || typeof newStatus !== 'string') {
      return res.status(400).json({ error: 'Bad Request', message: 'newStatus is required' });
    }

    const referral = await prisma.referral.findUnique({ where: { id } });
    if (!referral) return res.status(404).json({ error: 'Not Found', message: 'Referral not found' });

    const currentStatus = referral.status;
    
    // 24. REFERRAL STATE MACHINE: Reject invalid transitions
    if (!VALID_TRANSITIONS[currentStatus]?.includes(newStatus)) {
      return res.status(400).json({ error: 'Invalid Transition', message: `Cannot transition from ${currentStatus} to ${newStatus}` });
    }

    const cleanNotes = notes ? String(notes).trim().slice(0, 500) : undefined;

    const updated = await prisma.$transaction(async (tx) => {
      // 24. Record every transition in ReferralEvent
      await tx.referralEvent.create({
        data: {
          referralId: id,
          statusFrom: currentStatus,
          statusTo: newStatus,
          notes: cleanNotes
        }
      });

      const updatedRef = await tx.referral.update({
        where: { id },
        data: { status: newStatus },
        include: {
          patient: true,
          origin: true,
          destination: true,
          events: { orderBy: { createdAt: 'desc' } }
        }
      });

      return updatedRef;
    });

    // Part B & H: Emit REFERRAL_OPERATIONAL_UPDATE on transition
    broadcastReferralOperational(updated.originId, updated.destinationId, {
      referralId: updated.id,
      status: updated.status,
      urgency: updated.urgency,
      reason: updated.reason
    });

    res.json(updated);
  } catch (error) {
    res.status(500).json({ error: 'Internal Server Error' });
  }
};

export const listReferrals = async (req: Request, res: Response) => {
  try {
    const { destinationId, originId, status, urgency, patientId, specialty } = req.query;

    const where: any = {};
    if (destinationId) where.destinationId = String(destinationId);
    if (originId) where.originId = String(originId);
    if (status) where.status = String(status);
    if (urgency) where.urgency = String(urgency);
    if (patientId) where.patientId = String(patientId);

    if (specialty) {
      const spec = String(specialty).toLowerCase();
      where.reason = { contains: spec, mode: 'insensitive' };
    }

    const referrals = await prisma.referral.findMany({
      where,
      orderBy: { id: 'desc' },
      include: {
        patient: {
          include: {
            identifiers: true,
            assessments: {
              include: { symptoms: true, aiRecommendations: true },
              orderBy: { createdAt: 'desc' },
              take: 1
            }
          }
        },
        origin: true,
        destination: true,
        events: {
          orderBy: { createdAt: 'desc' }
        },
        counterReferral: true
      }
    });

    res.json(referrals);
  } catch (error) {
    res.status(500).json({ error: 'Internal Server Error' });
  }
};

export const getReferralById = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const referral = await prisma.referral.findUnique({
      where: { id },
      include: {
        patient: {
          include: {
            identifiers: true,
            assessments: {
              include: { symptoms: true, aiRecommendations: true },
              orderBy: { createdAt: 'desc' }
            }
          }
        },
        origin: true,
        destination: true,
        events: {
          orderBy: { createdAt: 'desc' }
        },
        counterReferral: true
      }
    });

    if (!referral) {
      return res.status(404).json({ error: 'Not Found', message: 'Referral not found' });
    }

    res.json(referral);
  } catch (error) {
    res.status(500).json({ error: 'Internal Server Error' });
  }
};
